version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez
        columns:
          - name: "(orders_id||'-'||pdt_id)"
            tests:
              - unique
              - not_null
          - name: date_date
            description: date of order
          - name: orders_id
            description: ID of an order
          - name: pdt_id
            description: product_id
          - name: revenue
            description: turnover
          - name: quantity
            description: How much was bought
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: primary_key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: Price of Product
      - name: ship
        identifier: raw_gz_ship
        description: shipment of Greenweez
        columns:
          - name: orders_id
            description: primary_key
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: How much the shipping fee is
          - name: log_cost
            description: some cost
          - name: ship_cost
            description: how much the shipping cost is version
 